In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/Users/sniperyyc/Documents/Research/CANGen/data/road/signal_extractions/ambient/accelerator_attack_drive_1.csv")
df.head()

df.shape

(192019, 25)

In [4]:
df.head()

,Label,Time,ID,Signal_1_of_ID,Signal_2_of_ID,Signal_3_of_ID,Signal_4_of_ID,Signal_5_of_ID,Signal_6_of_ID,Signal_7_of_ID,...,Signal_13_of_ID,Signal_14_of_ID,Signal_15_of_ID,Signal_16_of_ID,Signal_17_of_ID,Signal_18_of_ID,Signal_19_of_ID,Signal_20_of_ID,Signal_21_of_ID,Signal_22_of_ID
0,0,0.000000,1413,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,0.000002,852,32765,0.0,120.0,11.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0.000003,1505,511,1.0,3.0,1.0,0.0,32768.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,0.000004,651,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,0.000994,167,0,0.0,0.0,2.0,529.0,1.0,593.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
set(df['Label'])

{0}

In [9]:
df = pd.read_csv("/Users/sniperyyc/Documents/Research/CANGen/data/road/signal_extractions/attacks/accelerator_attack_drive_2.csv")

df.shape

(161371, 25)

In [10]:
df.head()

,Label,Time,ID,Signal_1_of_ID,Signal_2_of_ID,Signal_3_of_ID,Signal_4_of_ID,Signal_5_of_ID,Signal_6_of_ID,Signal_7_of_ID,...,Signal_13_of_ID,Signal_14_of_ID,Signal_15_of_ID,Signal_16_of_ID,Signal_17_of_ID,Signal_18_of_ID,Signal_19_of_ID,Signal_20_of_ID,Signal_21_of_ID,Signal_22_of_ID
0,0,0.000000e+00,1176,4095,4095.0,249.0,0.0,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,9.536743e-07,1124,0,0.0,20.0,1.0,1.0,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,1.907349e-06,470,0,0.0,7.0,2.0,1.0,0.0,0.0,...,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,3.099442e-06,560,-15,0.0,94.0,14.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,1.072884e-03,705,0,-100.0,-1.0,-109.0,1.0,1.0,173.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
set(df['Label'])

{0}

In [12]:
df = pd.read_csv("/Users/sniperyyc/Documents/Research/CANGen/data/road/signal_extractions/attacks/correlated_signal_attack_1_masquerade.csv")
df.shape

(74152, 25)

In [13]:
df.head()

,Label,Time,ID,Signal_1_of_ID,Signal_2_of_ID,Signal_3_of_ID,Signal_4_of_ID,Signal_5_of_ID,Signal_6_of_ID,Signal_7_of_ID,...,Signal_13_of_ID,Signal_14_of_ID,Signal_15_of_ID,Signal_16_of_ID,Signal_17_of_ID,Signal_18_of_ID,Signal_19_of_ID,Signal_20_of_ID,Signal_21_of_ID,Signal_22_of_ID
0,0,0.000000,852,32808,0.0,78.0,9.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,0.001020,1505,510,2.0,3.0,1.0,0.0,32846.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0.001021,651,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,0.001023,167,0,0.0,0.0,0.0,500.0,0.0,589.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,0.001024,208,9,631.0,0.0,0.0,2.0,496.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
set(df['Label'])

{0, 1}

In [15]:
# number of rows with label 0
df[df['Label'] == 0].shape

(72066, 25)

In [16]:
df = pd.read_csv("/Users/sniperyyc/Documents/Research/CANGen/data/road/signal_extractions/attacks/correlated_signal_attack_2_masquerade.csv")
print(df.shape)
print(df[df['Label'] == 0].shape)

(63260, 25)
(61121, 25)

In [17]:
df = pd.read_csv("/Users/sniperyyc/Documents/Research/CANGen/data/road/signal_extractions/attacks/correlated_signal_attack_3_masquerade.csv")
print(df.shape)
print(df[df['Label'] == 0].shape)

(38003, 25)
(36740, 25)